// User reducer types
export const HANDLE_DRAWER_TOGGLE = "HANDLE_DRAWER_TOGGLE";
export const SET_HEADER_TEXT = "SET_HEADER_TEXT";
export const SET_USER_COUNTRY = "SET_USER_COUNTRY";
export const LOADING_DATA = "LOADING_DATA";
export const DATA_LOADED = "DATA_LOADED";
export const SET_COUNTRIES = "SET_COUNTRIES";
export const STOP_LOADING = "STOP_LOADING";

export const SET_TAB_INDEX = "SET_TAB_INDEX";

// Algorithms
export const SET_ALGORITHM_TITLE = "SET_ALGORITHM_TITLE";
export const SET_CURRENT_ALGORITHM_INDEX = "SET_CURRENT_ALGORITHM_INDEX";
export const OPEN_ALGORITHM_DRAWER = "OPEN_ALGORITHM_DRAWER";
export const SET_CURRENT_ALGORITHM_SCREEN = "SET_CURRENT_ALGORITHM_SCREEN";

// Interview
export const SET_INTERVIEW_TITLE = "SET_INTERVIEW_TITLE";
export const SET_CURRENT_INTERVIEW_INDEX = "SET_CURRENT_INTERVIEW_INDEX";
export const OPEN_INTERVIEW_DRAWER = "OPEN_INTERVIEW_DRAWER";
export const SET_CURRENT_INTERVIEW_SCREEN = "SET_CURRENT_INTERVIEW_SCREEN";

// FreeMaterials
export const SET_FREE_MATERIAL_TITLE = "SET_FREE_MATERIAL_TITLE";
export const SET_CURRENT_FREE_MATERIAL_INDEX = "SET_CURRENT_FREE_MATERIAL_INDEX";
export const OPEN_FREE_MATERIAL_DRAWER = "OPEN_FREE_MATERIAL_DRAWER";
export const SET_CURRENT_FREE_MATERIAL_SCREEN = "SET_CURRENT_FREE_MATERIAL_SCREEN";

// Leetcodes
export const SET_LEETCODE_TITLE = "SET_LEETCODE_TITLE";
export const SET_CURRENT_LEETCODE_INDEX = "SET_CURRENT_LEETCODE_INDEX";
export const OPEN_LEETCODE_DRAWER = "OPEN_LEETCODE_DRAWER";
export const SET_CURRENT_LEETCODE_SCREEN = "SET_CURRENT_LEETCODE_SCREEN";

// Playground 
export const SET_PLAYGROUND_TITLE = "SET_PLAYGROUND_TITLE";


// Search
export const SET_SEARCH_TRUE = "SET_SEARCH_TRUE";
export const SET_SEARCH_FALSE = "SET_SEARCH_FALSE";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_SEARCH_STRING = "SET_SEARCH_STRING";

// UI
export const DARK_MODE_OFF = "DARK_MODE_OFF";
export const DARK_MODE_ON = "DARK_MODE_ON";
export const SET_NEW_USER_STATUS = "SET_NEW_USER_STATUS";
