import argonTheme from "../constants/Theme";

export const algorithmStyle = {
  'code[class*="language-"]': {
    color: "#c5c8c6",
    textShadow: "0 1px rgba(0, 0, 0, 0.3)",
    fontFamily:
      "Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace",
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    lineHeight: "4",
    MozTabSize: "4",
    OTabSize: "4",
    tabSize: "4",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#c5c8c6",
    textShadow: "0 1px rgba(0, 0, 0, 0.3)",
    fontFamily:
      "Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace",
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    lineHeight: "1.5",
    MozTabSize: "4",
    OTabSize: "4",
    tabSize: "4",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
    // padding: "1em",
    margin: ".5em 0",
    overflow: "auto",
    borderRadius: "0.3em",
    background: "#11111d",
  },

  ':not(pre) > code[class*="language-"]': {
    background: "#11111d",
  },

  comment: { color: "#7C7C7C" },
  prolog: { color: "#7C7C7C" },
  doctype: { color: "#7C7C7C" },
  cdata: {
    color: "#7C7C7C",
  },

  punctuation: {
    color: "#c5c8c6",
  },
  ".namespace": {
    opacity: ".7",
  },
  property: { color: "#96CBFE" },
  keyword: { color: "#96CBFE" },
  tag: {
    color: "#96CBFE",
  },

  "class-name": {
    color: "#FFFFB6",
    textDecoration: "underline",
  },

  boolean: { color: "#99CC99" },
  constant: {
    color: "#99CC99",
  },
  symbol: { color: "#f92672" },
  deleted: {
    color: "#f92672",
  },
  number: {
    color: "#FF73FD",
  },

  selector: { color: "#A8FF60" },
  "attr-name": { color: "#A8FF60" },
  string: { color: "#A8FF60" },
  char: { color: "#A8FF60" },
  builtin: { color: "#A8FF60" },
  inserted: {
    color: "#A8FF60",
  },
  variable: {
    color: "#C6C5FE",
  },
  operator: {
    color: "#EDEDED",
  },
  entity: {
    color: "#FFFFB6",
    cursor: "help",
  },
  url: {
    color: "#96CBFE",
  },

  ".language-css .token.string": {
    color: "#87C38A",
  },
  ".style .token.string": {
    color: "#87C38A",
  },

  atrule: { color: "#F9EE98" },
  "attr-value": {
    color: "#F9EE98",
  },

  function: {
    color: "#DAD085",
  },

  regex: {
    color: "#E9C062",
  },

  important: {
    fontWeight: "bold",
  },
  bold: {
    fontWeight: "bold",
  },

  italic: {
    fontStyle: "italic",
  },
};

export const algorithmStyle2 = {
  'code[class*="language-"]': {
    color: "#c5c8c6",
    textShadow: "0 1px rgba(0, 0, 0, 0.3)",
    fontFamily:
      '"Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    lineHeight: "1.5",
    MozTabSize: "4",
    OTabSize: "4",
    tabSize: "4",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#c5c8c6",
    textShadow: "0 1px rgba(0, 0, 0, 0.3)",
    fontFamily:
      '"Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    lineHeight: "1.5",
    MozTabSize: "4",
    OTabSize: "4",
    tabSize: "4",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
    margin: ".5em 0",
    overflow: "auto",
    borderRadius: "0.3em",
    background: "#081B33",
  },

  ':not(pre) > code[class*="language-"]': {
    background: "#081B33",
    padding: ".1em",
    borderRadius: ".3em",
  },
  comment: { color: "#7C7C7C" },
  prolog: { color: "#7C7C7C" },
  doctype: { color: "#7C7C7C" },
  cdata: { color: "#7C7C7C" },
  punctuation: { color: "#c5c8c6" },
  ".namespace": { Opacity: ".7" },
  property: { color: "#96CBFE" },
  keyword: { color: "#96CBFE" },
  tag: { color: "#96CBFE" },
  "class-name": { color: "#FFFFB6" },
  boolean: { color: "#99CC99" },
  constant: { color: "#99CC99" },
  symbol: { color: "#f92672" },
  deleted: { color: "#f92672" },
  number: { color: "#FF73FD" },
  selector: { color: "#A8FF60" },
  "attr-name": { color: "#A8FF60" },
  string: { color: "#A8FF60" },
  char: { color: "#A8FF60" },
  builtin: { color: "#A8FF60" },
  inserted: { color: "#A8FF60" },
  variable: { color: "#C6C5FE" },
  operator: { color: "#EDEDED" },
  entity: { color: "#FFFFB6", cursor: "help" },
  url: { color: "#96CBFE" },
  ".language-css .token.string": { color: "#87C38A" },
  ".style .token.string": { color: "#87C38A" },
  atrule: { color: "#F9EE98" },
  "attr-value": { color: "#F9EE98" },
  function: { color: "#DAD085" },
  regex: { color: "#E9C062" },
  important: { color: "#fd971f", fontWeight: "bold" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
};

const vs = {
  'code[class*="language-"]': {
    color: "#393A34",
    fontFamily:
      '"Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    fontSize: "0.95em",
    lineHeight: "1.2em",
    MozTabSize: "4",
    OTabSize: "4",
    tabSize: "4",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#393A34",
    fontFamily:
      '"Consolas", "Bitstream Vera Sans Mono", "Courier New", Courier, monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    fontSize: "0.95em",
    lineHeight: "1.2em",
    MozTabSize: "4",
    OTabSize: "4",
    tabSize: "4",
    WebkitHyphens: "none",
    MozHyphens: "none",
    msHyphens: "none",
    hyphens: "none",
    padding: "1em",
    margin: ".5em 0",
    overflow: "auto",
    border: "1px solid #dddddd",
    backgroundColor: "white",
  },
  'pre[class*="language-"]::-moz-selection': { background: "#C1DEF1" },
  'pre[class*="language-"] ::-moz-selection': { background: "#C1DEF1" },
  'code[class*="language-"]::-moz-selection': { background: "#C1DEF1" },
  'code[class*="language-"] ::-moz-selection': { background: "#C1DEF1" },
  'pre[class*="language-"]::selection': { background: "#C1DEF1" },
  'pre[class*="language-"] ::selection': { background: "#C1DEF1" },
  'code[class*="language-"]::selection': { background: "#C1DEF1" },
  'code[class*="language-"] ::selection': { background: "#C1DEF1" },
  ':not(pre) > code[class*="language-"]': {
    padding: ".2em",
    paddingTop: "1px",
    paddingBottom: "1px",
    background: "#f8f8f8",
    border: "1px solid #dddddd",
  },
  comment: { color: "#008000", fontStyle: "italic" },
  prolog: { color: "#008000", fontStyle: "italic" },
  doctype: { color: "#008000", fontStyle: "italic" },
  cdata: { color: "#008000", fontStyle: "italic" },
  namespace: { Opacity: ".7" },
  string: { color: "#A31515" },
  punctuation: { color: "#393A34" },
  operator: { color: "#393A34" },
  url: { color: "#36acaa" },
  symbol: { color: "#36acaa" },
  number: { color: "#36acaa" },
  boolean: { color: "#36acaa" },
  variable: { color: "#36acaa" },
  constant: { color: "#36acaa" },
  inserted: { color: "#36acaa" },
  atrule: { color: "#0000ff" },
  keyword: { color: "#0000ff" },
  "attr-value": { color: "#0000ff" },
  ".language-autohotkey .token.selector": { color: "#0000ff" },
  ".language-json .token.boolean": { color: "#0000ff" },
  ".language-json .token.number": { color: "#0000ff" },
  'code[class*="language-css"]': { color: "#0000ff" },
  function: { color: "#393A34" },
  deleted: { color: "#9a050f" },
  ".language-autohotkey .token.tag": { color: "#9a050f" },
  selector: { color: "#800000" },
  ".language-autohotkey .token.keyword": { color: "#00009f" },
  important: { fontWeight: "bold" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
  "class-name": { color: "#2B91AF" },
  ".language-json .token.property": { color: "#2B91AF" },
  tag: { color: "#800000" },
  "attr-name": { color: "#ff0000" },
  property: { color: "#ff0000" },
  regex: { color: "#ff0000" },
  entity: { color: "#ff0000" },
  "directive.tag  .tag": { background: "#ffff00", color: "#393A34" },
  ".line-numbers .line-numbers-rows": { borderRightColor: "#a5a5a5" },
  ".line-numbers-rows > span:before": { color: "#2B91AF" },
  ".line-highlight": {
    background:
      "linear-gradient(to right, rgba(193, 222, 241, 0.2) 70%, rgba(221, 222, 241, 0))",
  },
};
